# Generated by Django 3.2.1 on 2023-05-24 10:04

from django.db import migrations
import leaderboard.models


class Migration(migrations.Migration):

    dependencies = [
        ('leaderboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codecheffriends',
            name='id',
            field=leaderboard.models.HexadecimalAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='codeforcesfriends',
            name='id',
            field=leaderboard.models.HexadecimalAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='codeforcesuserratingupdate',
            name='id',
            field=leaderboard.models.HexadecimalAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='githubfriends',
            name='id',
            field=leaderboard.models.HexadecimalAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='leetcodefriends',
            name='id',
            field=leaderboard.models.HexadecimalAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='openlakefriends',
            name='id',
            field=leaderboard.models.HexadecimalAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
