# Generated by Django 3.2.1 on 2023-05-18 11:27

from django.db import migrations
import djongo.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('leaderboard', '0004_rename_id_customuser__id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='_id',
        ),
        migrations.AddField(
            model_name='customuser',
            name='id',
            field=djongo.models.fields.ObjectIdField(auto_created=True, default='', primary_key=True, serialize=False),
        ),
    ]
