# Generated by Django 3.2.1 on 2023-05-18 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leaderboard', '0005_auto_20230518_1127'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='id',
            new_name='_id',
        ),
    ]
